#!/usr/bin/env node

const program = require('commander');

program
  .version('1.0.0')
  .command('area', 'generates an area folder with an entry-level React component')
  .command('component', 'generates a React component')
  .parse(process.argv);