#!/usr/bin/env node

const inquirer = require('inquirer');
const path = require('path');
const componentTask = require('./src/tasks/component.js');
const { urlQuestion, typeQuestion, functionalQuestion, nameQuestion  } = require('./src/utils/component/questions.js');

const root = process.env.root || 'app';

const lastQuestion = (areaURL, componentType) => {
  inquirer.prompt([nameQuestion]).then(({ componentName }) => {
    componentTask(areaURL, componentName, componentType).then((componentsPath) => {
      console.log(`${componentName} in ${componentsPath} has been generated`);
    });
  });
};

inquirer.prompt([urlQuestion, typeQuestion]).then(answers => {
  const { areaURL, componentType } = answers;

  if (componentType === 'presentational') {
    inquirer.prompt([functionalQuestion]).then(({ isFunctional }) => {
      const componentType = isFunctional ? 'component_pure' : 'component';
      lastQuestion(areaURL, componentType);
    });
  } else {
    lastQuestion(areaURL, 'component_container');
  }
});